name: Deploy

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
    
      - name: Node Init
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Tools
        run: npm ci
        
      - name: Build Local
        run: npm run build
      
      - name: Copy Build to DGGProd
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          port: ${{ secrets.SCP_PORT }}
          key: ${{ secrets.SCP_KEY }}
          source: "build/*"
          rm: true
          target: ${{ secrets.SCP_TARGET }}
          strip_components: 1
          
      - name: Bust Varnish Cache 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          port: ${{ secrets.SCP_PORT }}
          key: ${{ secrets.SCP_KEY }}
          script: "sudo varnishadm \"ban req.http.host == positions.destiny.gg\""
        
